// -------------------------------Felhasználó tesztek-------------------------------


### Teszt: Felhasználó létrehozása
POST http://localhost:4000/users/register
Content-Type: application/json

{
  "username": "KonradTest",
  "email": "KonradTest@gmail.com",
  "password": "LegjobbTestes123",
  "address": "Hercegszántó, Tót u. 14."
}

### Felhasználó bejelentkezéses
POST http://localhost:4000/users/login
Content-Type: application/json

{
  "email": "somakoni1233@gmail.com",
  "password": "20060120Koni"
}

### User adatok lekérése (Admin szükséges)
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTI2ODkyNSwiZXhwIjoxNzM5MzU1MzI1fQ.Dp2Lje4hi78lsdIpFMAvLCQ-fBwdu5LgaRBYiRcN46E

Content-Type: application/json
{
}

### Felhasználók id alapján (Admin szükséges)
GET http://localhost:4000/users/3303eba2-5a8e-402d-8239-5da8b7ac71f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTI2ODkyNSwiZXhwIjoxNzM5MzU1MzI1fQ.Dp2Lje4hi78lsdIpFMAvLCQ-fBwdu5LgaRBYiRcN46E

Content-Type: application/json
{
}

### Felhasználó törlése id alapján (csak adminoknak)

DELETE http://localhost:4000/users/d852b419-a012-40bd-8327-828f7b2dce8c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTM0NzgxNiwiZXhwIjoxNzM5NDM0MjE2fQ.451uM2lvK-dnbCWTNPSwA525-Gz9gMeLxPxdZLSleCI

Content-Type: application/json
{
}


// -------------------------------Kategória tesztek-------------------------------

### Kategória szerinti szűrés
GET http://localhost:4000/ads/category/Ingatlan


### Kategória lekérés
GET http://localhost:4000/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFkZHJlc3MiOiIiLCJuYW1lIjoiS29ucmFkIiwiaWF0IjoxNzM5MzU4MTI1LCJleHAiOjE3Mzk0NDQ1MjV9.bocAnfNmLM4YhLRydk8qxHcoPsORKnj9BqaihilmWdM

Content-Type: application/json
{
}


// -------------------------------Hirdetés tesztek-------------------------------


### Hirdetés létrehozás
POST http://localhost:4000/ads
Content-Type: application/json

{
  "categoryID": "6", 
  "title": "Eladó Lenovo laptop", 
  "description": "Kiváló állapot, minden tartozékkal, 100%-os akkumulátor", 
  "price": 190000,
  "image": "image-lenovo.jpg"
}


### Hirdetés módosítás

PATCH http://localhost:4000/ads
Content-Type: application/json

{
  
}





