// -------------------------------Felhasználó tesztek-------------------------------
### Teszt: Felhasználó létrehozása
POST http://localhost:4000/users/register
Content-Type: application/json

{
  "username": "KonradTest12",
  "email": "KonradTest12@gmail.com",
  "password": "LegjobbTestes123",
  "address": "Hercegszántó, Tót u. 20."
}

### Felhasználó bejelentkezéses
POST http://localhost:4000/users/login
Content-Type: application/json

{
  "email": "KonradTest12@gmail.com",
  "password": "LegjobbTestes123"
}

### User adatok lekérése (Admin szükséges)
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFkZHJlc3MiOiIiLCJuYW1lIjoiS29ucmFkIiwiaWF0IjoxNzM5Nzg2NjEzLCJleHAiOjE3Mzk4NzMwMTN9.O45KVE5V3zfXiYb_FhJgL95CNzpj9yLAox4joFI3OzQ

Content-Type: application/json
{
}

### Felhasználók id alapján (Admin szükséges)
GET http://localhost:4000/users/9724ca4c-a576-4958-a829-aa4b12d1ce4b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFkZHJlc3MiOiIiLCJuYW1lIjoiS29ucmFkIiwiaWF0IjoxNzM5Nzg2NjgyLCJleHAiOjE3Mzk4NzMwODJ9.eJUDCovzeIufbAFEIKl2KFtAuNWwwLCkBz-HDoIuffc

Content-Type: application/json
{
}

### Felhasználó törlése id alapján (csak adminoknak)
DELETE http://localhost:4000/users/9724ca4c-a576-4958-a829-aa4b12d1ce4b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFkZHJlc3MiOiIiLCJuYW1lIjoiS29ucmFkIiwiaWF0IjoxNzM5Nzg2NjgyLCJleHAiOjE3Mzk4NzMwODJ9.eJUDCovzeIufbAFEIKl2KFtAuNWwwLCkBz-HDoIuffc


// -------------------------------Kategória tesztek-------------------------------

### Kategória szerinti szűrés (Kategória + kategóriához tartozó hirdetések)
GET http://localhost:4000/ads/category/Gépjármű

### Összes kategória lekérés
GET http://localhost:4000/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk3MjRjYTRjLWE1NzYtNDk1OC1hODI5LWFhNGIxMmQxY2U0YiIsImVtYWlsIjoiS29ucmFkVGVzdEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImFkZHJlc3MiOiJIZXJjZWdzesOhbnTDsywgVMOzdCB1LiAxNC4iLCJuYW1lIjoiS29ucmFkVGVzdCIsImlhdCI6MTczOTc4NDY2MSwiZXhwIjoxNzM5ODcxMDYxfQ.MFBLcM3hA-G8_Cv2ibAUlBY5EIZVeyw7JUbtUU4UeYA

// -------------------------------Hirdetés tesztek-------------------------------


### Hirdetés létrehozás
POST http://localhost:4000/ads
Content-Type: application/json

{
  "categoryID": "1", 
  "title": "Pumba", 
  "description": "Áron2Pumba is hadd örüljön", 
  "price": 50000,
  "image": "pumbaaron2.jpg"
}

### Hirdetés módosítás  
PATCH http://localhost:4000/ads/5508b232-661d-4f80-9a9f-9650a4d76434
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFkZHJlc3MiOiIiLCJuYW1lIjoiS29ucmFkIiwiaWF0IjoxNzM5NzgyMTk1LCJleHAiOjE3Mzk4Njg1OTV9.tu1px7FSrDWb_5SJg4qOLATCU5zo60wpLPnRZy89X_s
Content-Type: application/json

{
  "categoryID": "8",  
  "title": "Legkomolyabb hirdetés igenigen", 
  "description": "Ez egy módosított hirdetés leírása, amit nagyon nyomattam", 
  "price": 2000000,
  "image": "new-image.jpg"
}

### Hirdetés törlése

DELETE http://localhost:4000/ads/456eb044-8d77-4d20-b373-58c605515fff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFkZHJlc3MiOiIiLCJuYW1lIjoiS29ucmFkIiwiaWF0IjoxNzM5NzgzMzgyLCJleHAiOjE3Mzk4Njk3ODJ9.TJ9BQ38634Bo48u9gQcphZPE0FEHxQ-9MKpJNGFUr_w


### Összes hirdetés lekérése
GET http://localhost:4000/ads
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFkZHJlc3MiOiIiLCJuYW1lIjoiS29ucmFkIiwiaWF0IjoxNzM5MzU4MTI1LCJleHAiOjE3Mzk0NDQ1MjV9.bocAnfNmLM4YhLRydk8qxHcoPsORKnj9BqaihilmWdM

Content-Type: application/json
{
}