### Teszt: Felhasználó létrehozása
POST http://localhost:4000/users/register
Content-Type: application/json

{
  "username": "Armin",
  "email": "pecas@gmail.com",
  "password": ""
}

### Felhasználó bejelentkezéses
POST http://localhost:4000/users/login
Content-Type: application/json

{
  "email": "somakoni1233@gmail.com",
  "password": "20060120Koni"
}

### User adatok lekérése (Admin szükséges)
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTI2ODkyNSwiZXhwIjoxNzM5MzU1MzI1fQ.Dp2Lje4hi78lsdIpFMAvLCQ-fBwdu5LgaRBYiRcN46E

Content-Type: application/json
{
}

### Felhasználók id alapján (Admin szükséges)
GET http://localhost:4000/users/c2e378a9-454c-4041-b610-f6469e1d75a6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzMDNlYmEyLTVhOGUtNDAyZC04MjM5LTVkYThiN2FjNzFmNiIsImVtYWlsIjoic29tYWtvbmkxMjMzQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTI2ODkyNSwiZXhwIjoxNzM5MzU1MzI1fQ.Dp2Lje4hi78lsdIpFMAvLCQ-fBwdu5LgaRBYiRcN46E

Content-Type: application/json
{
}








